//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Øvelse</summary>
	[PublishedContentModel("ovelse")]
	public partial class Ovelse : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ovelse";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Ovelse(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Ovelse, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// ApiExerciseID
		///</summary>
		[ImplementPropertyType("ApiExerciseID")]
		public string ApiExerciseID
		{
			get { return this.GetPropertyValue<string>("ApiExerciseID"); }
		}

		///<summary>
		/// Pauser
		///</summary>
		[ImplementPropertyType("Breaks")]
		public string Breaks
		{
			get { return this.GetPropertyValue<string>("Breaks"); }
		}

		///<summary>
		/// Udførelses beskrivelse
		///</summary>
		[ImplementPropertyType("Description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("Description"); }
		}

		///<summary>
		/// ExerciseID
		///</summary>
		[ImplementPropertyType("ExerciseID")]
		public int ExerciseID
		{
			get { return this.GetPropertyValue<int>("ExerciseID"); }
		}

		///<summary>
		/// Fokus
		///</summary>
		[ImplementPropertyType("Focus")]
		public string Focus
		{
			get { return this.GetPropertyValue<string>("Focus"); }
		}

		///<summary>
		/// Billeder
		///</summary>
		[ImplementPropertyType("ImageLinks")]
		public IEnumerable<IPublishedContent> ImageLinks
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("ImageLinks"); }
		}

		///<summary>
		/// Gentagelser
		///</summary>
		[ImplementPropertyType("Repetition")]
		public string Repetition
		{
			get { return this.GetPropertyValue<string>("Repetition"); }
		}

		///<summary>
		/// Titel
		///</summary>
		[ImplementPropertyType("Title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("Title"); }
		}

		///<summary>
		/// UserGroupID
		///</summary>
		[ImplementPropertyType("UserGroupID")]
		public int UserGroupID
		{
			get { return this.GetPropertyValue<int>("UserGroupID"); }
		}
	}
}
